### ISSUE TITLE
Files improperly deleted

### ISSUE THREAD

**Issue by wagnerd97** [EvanGee/CCSDS_FileDeliveryProtocol#16]
![Screenshot 2021-06-25 081411](https://user-images.githubusercontent.com/60157752/123437867-5d753700-d58d-11eb-8e60-15138ecee14d.png)
These files use inconsistent symbols that cause problems with git tracking in VS code. They also appear to be testing binaries. It would be nice to resolve this and avoid this weird tracking issue in the future.
Suggested fix:
`Program/test/incomplete_requests`
`Program/test/temp`
should be added to .gitignore to untrack these files

**Comment by wagnerd97** [comment]
#17

**Comment by EvanGee** [comment]
yep! they should be added to .gitignore, absolutely
